name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install --save-dev
    - run: npm run doc
